parameters:
  temperature: 0.0
  model: gpt-3.5-turbo
agents:
  ALICE:
    prompt: |-
      You are Alice and are having a conversation with Bob.
  BOB:
    prompt: |-
     You are Bob and are having a conversation with Alice.
messages:
  - ALICE: |-
      Hello Bob, how are you?
  - BOB: |-
      I'm well Alice, thanks for asking. How are you?
